development:
  adapter: postgresql
  encoding: unicode
  database: indiegaga_dev
  pool: 5
  username: RbyWoo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: indiegaga_test
  pool: 5
  username: RbyWoo
  password:
